PROGRAM STOP END

SUBROUTINE RETURN END
SUBROUTINE ( RETURN END
SUBROUTINE ) RETURN END

SUBROUTINE A RETURN END
SUBROUTINE A ( RETURN END
SUBROUTINE A ) RETURN END
SUBROUTINE A (B,) RETURN END


FUNCTION A(B,C) RETURN END
